service: egov-adapter-traffic-radars

provider:
  name: aws
  runtime: python3.7
  memorySize: 3000
  timeout: 35  # API Gateway has a 30-seconds timeout in any case
  region: eu-west-1
  stage: dev
  versionFunctions: false
  environment:
    maintainer: egov

functions:
  adapt:
    handler: handler.adapt
    events:
      - http:
          path: "{proxy+}"
          method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
